#################
### AUTOSTART ###
#################

exec-once = fcitx5 &
exec-once = waybar
exec-once = hyprpaper
exec-once = awww-daemon
exec-once = sleep 2 && ~/.config/hypr/scripts/change-wallpaper.sh
