#################
### AUTOSTART ###
#################

exec-once = fcitx5 &
exec-once = waybar
exec-once = swww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper-rotation.sh > ~/.cache/wallpaper-rotation.log 2>&1
