################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

# 快捷键
source = ~/.config/hypr/keyboard.conf
# 窗口规则
source = ~/.config/hypr/rules.conf
# 开机自启动
source = ~/.config/hypr/autostart.conf
# 环境变量
source = ~/.config/hypr/env.conf
# 外观
source = ~/.config/hypr/ui.conf


#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = ctrl:nocaps
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
