###################
### WINDOW RULES ###
###################

# 文件对话框
windowrule = float, class:^(thunar|google-chrome|chromium)$, title:^(.*文件.*|.*保存.*|.*打开.*)

windowrule = float, class:^(Alacritty)$, title:^(alacritty -e \./system-update\.sh.*)

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
